peasant = [
            "Ready to serve."
            , "Yes?"
            , "My lord?"
            , "What is it?"
            , "Hello."
            , "Okay."
            , "Alright."
            , "Yes my lord!"
            , "Job's done."
            , "Oh, what?"
            , "Y-huh?"
            , "Now what?"
            , "More work?"
            , "Leave me alone!"
            , "I don't want to do this!"
            , "I'm not listening!"
        ]
footman = [
    "Awaiting orders."
    , "Your command?"
    , "Your orders?"
    , "Yes, sire?"
    , "Yes?"
    , "My lord?"
    , "At your service."
    , "Yes."
    , "Yes, my lord."
    , "As you wish."
    , "At once, sire."
    , "Make up your mind."
    , "Are you still touching me?"
    , "Don't you have a kingdom to run?"
    , "I do have work to do."
    , "'Join the army,' they said."
    , "'See the world,' they said."
    , "I'd rather be sailing."
]
archer = [
    "I come to serve."
    , "Your Eminence?"
    , "Exalted one?"
    , "My sovereign?"
    , "Your wish?"
    , "Yes."
    , "By your command."
    , "For the Alliance."
    , "Move out."
    , "We must take action."
    , "Time is of the essence."
    , "Even elder races get tired of waiting."
]
knight = [
    "Ready to serve, my lord."
    , "Your majesty?"
    , "At your service."
    , "Sire?"
    , "What ho!"
    , "We move."
    , "In your name."
    , "For the king."
    , "Defending your honour."
    , "I need orders."
    , "Give me a quest!"
    , "Don't force me to run you through!"
]
gnomes = [
    "I've got a flying machine!"
    , "Hello, sonny."
    , "Want me to fly?"
    , "Are you listening?"
    , "I'm flying…"
    , "Goodbye…"
]
dwarves = [
    "Dwarves ready."
    , "What do you want?"
    , "Ach?"
    , "Aye laddy."
    , "Okay."
    , "Alright."
    , "Move out."
    , "Yes sir."
    , "I love blowin' things up! 💣"
    , "Bombs are great! 💣"
    , "Tilt one back with me, dog! 🍻"
]
mage = [
    "Who summoned me?"
    , "What is it?"
    , "Do you need assistance?"
    , "Your request?"
    , "As you wish."
    , "Very well."
    , "Alright."
    , "I'm a busy man."
    , "Don't anger me."
    , "I warned you! 🌩️"
]
alliance_ships = [
    "Captain on the bridge."
    , "Aye, captain?"
    , "Skipper?"
    , "Set sail?"
    , "Aye, aye, sir."
    , "Aye, Captain."
    , "Underway."
    , "Work completed."
    , "Stop rocking the boat!"
    , "You're making me seasick!"
    , "🤮"
]
peon = [
    "Ready to work."
    , "Your command, master."
    , "Zok tok."
    , "Itok."
    , "Er?"
    , "Huh?"
    , "Ur-ur-urh!"
    , "Glor dook."
    , "Zug Zug."
    , "Dabu."
    , "Swobu."
    , "Lok'tar."
    , "Work complete."
    , "We're being attacked!"
    , "They're destroying our city!"
    , "WHAAAAT?!"
    , "Look out!"
    , "Missed me!"
    , "Hee hee hee! That tickles."
    , "I would not do such things if I were you."
    , "My tummy feels funny. 🥴"
    , "🥴 <burp> 'scuse me."
    , "You're good looking for a human."
        ]
troll = [
    "New troll here!"
    , "Joo call me?"
    , "Joo want axe?"
    , "What joo wan'me kill?"
    , "Okay."
    , "Alright."
    , "You da boss."
    , "I got axe for you!"
    , "🤬"
    , "Say hello to my little friend!"
]
ogre = [
    "We're ready, master.\nI'm not ready."
    , "Huh?/nWhat?"
    , "What?\nHuh?"
    , "Yes?"
    , "Master?"
    , "Okay."
    , "Yes, master."
    , "Alright."
    , "Yes, master."
    , "I don't want to!"
    , "All right."
    , "Now I'm hungry."
    , "This way.\nNo, that way!"
    , "🥴 <burp> He did it!\nNo, he did it!"
    , "💨 <fart> 😆\n😆"
]
ogre_mage = [
    "We're ready, master."
    , "Yes, master?"
    , "What?"
    , "Yes?"
    , "What is it?"
    , "Yes, master."
    , "Of course."
    , "Right away."
    , "🥴 <burp> We did it."
    , "We're not brainless anymore."
    , "I've got the brain.\nNuh-uh!"
]
zeppelin = [
    "Here I am."
    , "I can see my house!"
    , "I wish I had a weapon!"
]
death_knight = [
    "I'm alive!"
    , "Yes?"
    , "Make it quick."
    , "Of course... master."
    , "Very well."
    , "I'm growing impatient."
    , "Don't push it."
    , "When my work is finished, I'm coming back for you."
]
goblins = [
    "We're ready."
    , "What?"
    , "Yes?"
    , "Who is it?"
    , "Hello?"
    , "Okay."
    , "Certainly."
    , "Yes, boss."
    , "All right."
    , "We've got explosives! 💣"
    , "💣 KABOOM!"
    , "Awww, it's beautiful!"
]
horde_ships = [
    "Done building ship."
    , "Arg?"
    , "Aye, matey?"
    , "Yes, Captain?"
    , "Ahoy."
    , "I would love to."
    , "You're the captain."
    , "Yo ho!"
    , "Who wants to sing?"
    , '🎵🎵'
]

alliance = [peasant, footman, archer, knight, gnomes, dwarves, mage, alliance_ships]
horde = [peon, troll, ogre, ogre_mage, zeppelin, death_knight, goblins, horde_ships]
